name: Docker Back

on:
  push:
    branches:
      - main
      
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: release-backend

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: builder the docker image
      run: |
        cd backend
        docker buildx build --platform linux/amd64,linux/arm64 -t depwegk/big_data_and_the_cloud:backend_latest .
        
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push DockerImage
      uses: docker/build-push-action@v4
      with:
        context: backend/
        push: true
        tags: depwegk/big_data_and_the_cloud:backend_latest
        platforms: linux/amd64,linux/arm64
