name: Docker Front

on:
  push:
    branches:
      - main
      
jobs:
  
  build_frontend:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Switch to feature-frontend branch
      run: git checkout feature-frontend

    - name: builder the dcker image
      run: docker build -t frontend .
