name: Docker Front

on:
  push:
    branches:
      - main
      
jobs:
  
  build_frontend:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: jupyter

    - name: builder the docker image
      run: |
        docker build -t frontend .

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push DockerImage
      uses: docker/build-push-action@v4
      with:
        context: /
        push: true
        tags: depwegk/big_data_and_the_cloud:jupyter_latest
