name: Docker Jupyter

on:
  push:
    branches:
      - feature-jupyter
      
jobs:
  
  build_jupyter:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: feature-jupyter

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: builder the docker image
      run: |
        cd jupyter
        docker buildx build --platform linux/amd64,linux/arm64 -t depwegk/big_data_and_the_cloud:jupyter_latest .

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #-  uses: docker/build-push-action@v4
    #  with:
    #    context: jupyter/
    #    push: true
    #    tags: depwegk/big_data_and_the_cloud:jupyter_latest
    #    platforms: linux/amd64,linux/arm64
